name: nyt
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: 0.18.1
  url_strategy: 0.2.0
  go_router: 10.0.0
  flutter_riverpod: 
  riverpod_annotation: 
  flutter_layout_grid: 2.0.4
  rxdart: 0.27.7
  webview_flutter: 4.2.2
  http: 1.1.0
  cached_network_image: 3.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner:
  riverpod_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
